apiVersion: v1
kind: Service
metadata:
  labels:
    app: sftp-dced
  name: bur-sftp-dced-svc
#  namespace: gr-sftp-server (uncomment when create manually)
spec:
  loadBalancerIP:
  type: LoadBalancer
  ports:
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  selector:
    app: sftp-dced
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack