---
# Common details
ENV_NAME:  # The environment name

# CCD details
NAMESPACE:  # A namespace of the EO installation
CCD_KUBECONFIG_PATH:  # EO Kubeconfig file path
HELM_REGISTRY_HOST:  # EO Helm registry host address

# EVNFM details
EVNFM_HOST:  # EVNFM host

EVNFM_DEFAULT_USER_NAME:  # EVNFM default username
EVNFM_DEFAULT_USER_PASSWORD:  # EVNFM default password
EVNFM_DEFAULT_TENANT:  # EVNFM default tenant name
PV_STORAGE_CLASS:  # A value of eric-pm-server.server.persistentVolume.storageClass

EVNFM_USER_NAME:  # non-default EVNFM username
EVNFM_USER_PASSWORD:  # non-default EVNFM password

# Registry details
GLOBAL_REGISTRY_HOST:  # Global registry host address
DOCKER_REGISTRY_HOST:  # Docker registry host address
REGISTRY_USER_NAME:  # Docker registry username
REGISTRY_USER_PASSWORD:  # Docker registry password

# Certificate details
INTERMEDIATE_CERTIFICATE_PATH: # specify relative-path to intermediate certificate in submodule repo. Eg: <submodule_repo_name>/<path_to_cert>,
# for App Staging setup "eo-integration-ci" is used as submodule with cert, for RV "eo-install"
