---
# SFTP Server details
SFTP_NAMESPACE: sftp-dced
SFTP_CLUSTER_NAME: !from_key env_nfvi-3.yaml:ENV_NAME
SFTP_KUBE_CONFIG: !from_key env_nfvi-3.yaml:CCD_KUBECONFIG_PATH
SFTP_EXT_IP_ADDRESS: 10.227.49.132
SFTP_USER_NAME: ericsson
SFTP_PASSWORD: ericsson

# DNS Server details
DNS_SERVER_NAMESPACE:
DNS_SERVER_CLUSTER_NAME:
DNS_SERVER_KUBE_CONFIG:
DNS_SERVER_EX_IP_ADDRESS: