apiVersion: v1
kind: Service
metadata:
  labels:
    app: gr-iperf
  name: gr-iperf-svc
  namespace: gr-iperf
spec:
  loadBalancerIP:
  type: LoadBalancer
  ports:
  - name: iperf3
    port: 5201
    protocol: TCP
    targetPort: 5201
  selector:
    app: gr-iperf
  sessionAffinity: None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack