---
url: http://10.232.14.15
vim_host: 10.232.14.15
vim_ip: 10.232.14.15
vim_object_id: b3d97ab341214c5483753278c6f5cdb2
os_admin_name: eo-admin
os_admin_password: foobar
os_admin_vim_object_id: 9c43385eefca438a919c6266565d2da6
os_user_name: user
os_user_password: foobar
os_user_vim_object_id: 40befcdfc02c4f25b98122520a791b94
os_ssh_user: root
os_ssh_password: _rdoctrl_

vim_type: OPENSTACK

default_os_admin_name: admin
default_os_admin_password: 30ef26f6c95646e8
default_os_project_name: admin

auth_url: http://10.232.14.15:5000/v3
project_name: Ericsson
os_project_domain_id: default
os_user_domain_name: Default

# rdo endpoint ports section:
endpoints:
  - keystone:
      - version: 3.0
      - port: 5000
      - uri: /
  - neutron:
      - version: 2.0
      - port: 9696
      - uri: /
  - nova:
      - version: 2.1
      - port: 8774
      - uri: /v2.1
  - heatstack:
      - version: 1.0
      - port: 8004
      - uri: /v1
  - glance:
      - version: 2.0
      - port: 9292
      - uri: /v1
  - cinder:
      - version: 2.0
      - port: 8776
      - uri: /v2
  - gnocchi:
      - version: 1.0
      - port: 8041
      - uri: /
